blogProject/Models/postViewModel.cs
using BlogDal;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace blogProject.Models
{
    public class postViewModel
    {
        public IEnumerable<post> posts { get; set; }
    }
}

blogProject/Controllers/ChatController.cs
using BlogDal;
using BlogDal.Abstract;
using blogProject.Helper;
using Microsoft.AspNet.SignalR;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace blogProject.Controllers
{
    public class CustomJsonResult : JsonResult
    {
        private const string _dateFormat = "yyyy-MM-dd HH:mm:ss";

        public override void ExecuteResult(ControllerContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException("context");
            }

            HttpResponseBase response = context.HttpContext.Response;

            if (!String.IsNullOrEmpty(ContentType))
            {
                response.ContentType = ContentType;
            }
            else
            {
                response.ContentType = "application/json";
            }
            if (ContentEncoding != null)
            {
                response.ContentEncoding = ContentEncoding;
            }
            if (Data != null)
            {
                // Using Json.NET serializer
                var isoConvert = new IsoDateTimeConverter();
                isoConvert.DateTimeFormat = _dateFormat;
                response.Write(JsonConvert.SerializeObject(Data, isoConvert));
            }
        }
    }// end of class
    public class grouoMessageViewModel
    {
        public int groupChatId { get; set; }
        public int uid { get; set; }
        public string name { get; set; }
        public string msg { get; set; }
        public string groupd { get; set; }
        public string time { get; set; }
        public string txtType { get; set; }
    }
    public class ChatController : Controller
    {
        public IgroupRepository gRepository;
        private IuserRepository repository;

        // GET: Chat
        private static string SessionKey = "userId";

        public  ChatController(IgroupRepository prmRepository,IuserRepository prmUserRepository)
        {
            gRepository = prmRepository;
            repository = prmUserRepository;
        }
        [HttpGet]
        public  ActionResult getFiles(int groupId)
        {
            var values = (from x in gRepository.groupChats
                       where (x.groupId == groupId && x.txtType == "imagetxt")
                       select new {userId = x.userId, fileName = x.chatTxt }).ToList();

            //var values= gRepository.getFileNames(groupId);
            return Json(values, JsonRequestBehavior.AllowGet);

        }
        

        [HttpGet]
        public ActionResult getChat(int groupId,int pageCount)
        {
            int groupToMestalsages = gRepository.GroupMessageTotal(groupId);
            int skippTotal = pageCount * 30;
            if (skippTotal<groupToMestalsages && (groupToMestalsages-skippTotal)<30 )
            {
                skippTotal = groupToMestalsages;

            }
            var groupChat = (from p in gRepository.groupChats
                             where p.groupId == groupId
                             select new
                             {
                                 groupChatId = p.groupChatId,
                                 uid = p.userId,
                                 name = p.users.userName,
                                 msg = p.chatTxt,
                                 groupd = p.groups.groupName,
                                 time = p.txtDate,
                                 txtType = p.txtType
                             }).
                            ToList()
                            .Select(x => new grouoMessageViewModel()
                            {
                                groupChatId=x.groupChatId,
                                uid=x.uid,
                                name=x.name,
                                msg=x.msg,
                                groupd=x.groupd,
                                time=x.time.ToString("s"),
                                txtType=x.txtType


                            }).ToList().Skip(groupToMestalsages-skippTotal).Take(skippTotal);
                            

            
               
             
              //  Select(x => new { groupChatId = x.groupChatId, uid = x.users.userId, name = x.users.userName, msg = x.chatTxt, group = x.groups.groupName, time = x.txtDate, txtType = x.txtType });
            return Json(groupChat, JsonRequestBehavior.AllowGet);
           // return new CustomJsonResult { Data = new { chats = groupChat } };

        }
        [HttpPost]
        public JsonResult SaveFiles(string description)
        {
            string Message, fileName, actualFileName;
            Message = fileName = actualFileName = string.Empty;
            bool flag = false;
            string path = "";
            if (Request.Files != null)
            {
                var file = Request.Files[0];
                actualFileName = file.FileName;
                fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
                int size = file.ContentLength;
                try
                {
                    path = Server.MapPath("~/Images");
                    file.SaveAs(Path.Combine(path, fileName));

                    Message = fileName;
                    flag = true;

                }
                catch (Exception)
                {
                    Message = "Failed";

                    flag = false;
                }


            }

            return new JsonResult { Data = new { Message = Message, Status = flag } };
        }
        public ActionResult testing()
        {
            return View();
        }
        [HttpGet]
        [Route("ChatController")]

        public ActionResult getUserId ()
        {
            var userDetails = ControllerContext.HttpContext.Session[SessionKey];
            return Json(userDetails, JsonRequestBehavior.AllowGet);

        }
        [HttpGet]
        public ActionResult verifyUserAndGetUser(string userName, string password, HttpRequestMessage request)
        {
          // var d= request.GetClientIpAddress();
            user prmUser = new user
            {
                userName = userName,
                password = password
            };
            user dbUser = repository.verifyUser(prmUser);
            //    FormsAuthentication.SetAuthCookie("junaid",false); // This statment is for Temporarly purpose  only 
            if (dbUser != null)
            {
                User usr = new User();
                usr.userId = dbUser.userId;
                usr.name = dbUser.userName;
                this.HttpContext.Session.Timeout = 60;
                ControllerContext.HttpContext.Session[SessionKey] = usr;

                
                 var ip = this.Request.ServerVariables["REMOTE_ADDR"];
                //ip = "92.0.164.122";
                var country = Helper.GeoLocation.IPRequestHelper(ip);
                repository.saveCountry(dbUser.userId, country);
            }
            var userDetails = ControllerContext.HttpContext.Session[SessionKey];
            if (userDetails!=null)
            {
               return  RedirectToAction("ChatRoom", "chat");

            }

            return Json(userDetails, JsonRequestBehavior.AllowGet);


        } // end of action Method
        [HttpGet]
        public ActionResult registerNewUser(string name,string password)
        {
            User usr = new User();

            user prmUser = new user()
            {
                userName=name,
                password=password
            };
            if (repository.checkUser(prmUser))
            {
                
            }
            else
            {
                repository.Create(prmUser);
                usr.userId = prmUser.userId;
                usr.name = prmUser.userName;
                ControllerContext.HttpContext.Session[SessionKey] = usr;
            }
            return Json(usr, JsonRequestBehavior.AllowGet);


        }
        [HttpGet]
        public ActionResult getId()
        {
            var userDetails = ControllerContext.HttpContext.Session[SessionKey];
            return Json(userDetails, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ChatRoom()
        {
            //if (ControllerContext.HttpContext.Session["UserId"] == null)
            //{
            //    ViewBag.invalid = "You need to give Log Dtails to Start Chatting ....";
            //  return RedirectToAction("LogPagee", "Account",new {returnUrl= Request.RawUrl } );
            //}
            //else 
            return View();
        }
        public ActionResult chatManage()
        {
            return View();
        }
        public ActionResult postChat(int postId)
        {
            ControllerContext.HttpContext.Session["postId"] = postId;
            return View();
        }
        public ActionResult mapChat()
        {
            return View();
        }
    }
}

blogProject/Controllers/NavController.cs
using BlogDal.Abstract;
using blogProject.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace blogProject.Controllers
{
    public class NavController : Controller
    {
        private IpostRepository repositoty;
        // GET: Nav
        public NavController(IpostRepository prmRepositoty)
        {
            repositoty = prmRepositoty;
        }
        [ChildActionOnly]
      //  [OutputCache(Duration =60)]
        public PartialViewResult postCategory()
        {
            categoriesViewModel catViewModel = new categoriesViewModel();
            catViewModel.listCategories =  repositoty.categories.ToList();

            return  PartialView(catViewModel);
        }
        [ChildActionOnly]
      //  [OutputCache(Duration = 60)]
        public PartialViewResult postList ()
        {
            postViewModel listPosts = new postViewModel();
            listPosts.posts = repositoty.posts.OrderByDescending(c=>c.createDate).Take(10);
            return PartialView(listPosts);
        }
        [ChildActionOnly]
       // [OutputCache(Duration = 60)]
        public PartialViewResult recentComments()
        {
            commentsListViewModel commentsViewModel = new commentsListViewModel();
            commentsViewModel.commentsList = repositoty.comments.OrderByDescending(d => d.commentDate).Take(10);
            return PartialView(commentsViewModel);

        }
        [ChildActionOnly]
       // [OutputCache(Duration = 60)]
        public PartialViewResult archiveList()
        {
            archiveViewMode listViewMonth = new archiveViewMode();
            //listViewMonth.monthsList = new Dictionary<string, int>();
           // var archiveList=    repositoty.posts.Select(c => new { c.createDate.Month, c.createDate.Year }).Distinct();
            listViewMonth.listArchive = (IList<archive>)
                                        (from post in repositoty.posts
                                         select new archive {Month=  post.createDate.Month,Year=post.createDate.Year }).Distinct().ToList();

            //for (int month =1; month<=12;month++)
            //{
            //    var value = repositoty.posts.Where(p => p.createDate.Month == month).Count();
            //    listViewMonth.monthsList.Add(DateTimeFormatInfo.CurrentInfo.GetMonthName(month) , value);
            //}
            //foreach (var mon in archiveList)
            //{
            //    listViewMonth.monthsList.Add(DateTimeFormatInfo.CurrentInfo.GetMonthName(mon.Month)+"(" + mon.Year + ")"  , mon.Year);
            //}
            foreach (var arch in listViewMonth.listArchive)
            {
                arch.MonthName = DateTimeFormatInfo.CurrentInfo.GetMonthName(arch.Month);
            }

           
            return PartialView(listViewMonth);
        }

        
        public PartialViewResult LogInnandOut()
        {
            
            LoguserViewModel logUser = new LoguserViewModel();
           
            if ( ControllerContext.HttpContext.Session["UserId"]!=null)
            {
                User dbuser = (User) ControllerContext.HttpContext.Session["UserId"];
                logUser.userName = dbuser.name;
                logUser.Id = dbuser.userId;
            }

            return PartialView(logUser);

        }
        
        public User getUserId ()
        {
            User dbuser = new User();
            if (ControllerContext.HttpContext.Session["UserId"] != null)
            {
                 dbuser = (User)ControllerContext.HttpContext.Session["UserId"];
              
            }
            return dbuser;

        }
        [ChildActionOnly]

        public PartialViewResult leaveComment(int postId,string postName)
        {
            leaveCommentModel dbcomment = new leaveCommentModel();
            dbcomment.postId = postId;
            dbcomment.postName = postName;
            if (ControllerContext.HttpContext.Session["UserId"] != null)
            {
                dbcomment.loged = true;
            }
            else
            {
                dbcomment.loged = false;
            }
            return PartialView(dbcomment);
        }
        public PartialViewResult AdminOptions()
        {
            return PartialView();
        }
        public PartialViewResult postFavourite()
        {
            User userInfo = getUserId();
            favouriteViewModel favPostList = new favouriteViewModel();
            if (userInfo.userId!=0)
            {
                favPostList.userId = userInfo.userId;

                favPostList.favPostList = repositoty.favPosts.Where(d => d.userId == userInfo.userId).OrderByDescending(c => c.favDate).Take(10);

            }
            else
            {
                favPostList.userId = 0;

            }

            return PartialView(favPostList);
        }
    }
}

blogProject/Views/Post/postList.cshtml
@model blogProject.Models.categoryPostsViewModel

@{
    ViewBag.Title = "postList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

        <div class="panel-body">
            <h1 class="page-header">
                @Model.postCategory
                <small> list of posts .. </small>
            </h1>
            @if (Model.posts.Count() <= 0)
            {
                <div class="panel panel-danger">
                    <div class="panel-heading"><h4>Post Search Error <span class="glyphicon glyphicon-question-sign"></span> </h4></div>
                    <div class="panel-body">No Post Added for <label class="btn-danger"> @Model.postCategory</label></div>
                </div>
                
            }
            <!-- First Blog Post -->
            @foreach (var p in Model.posts)
            {
                <div class="row">
                    <div class="col-lg-12">
                <h4>
                    @Html.RouteLink(@p.postName, new
                       {
                           controller = "Post",
                           action = "viewPost",
                           postId = p.postId
                       })
                    <span class="label label-danger">
                        @p.comments.Count()
                        comments <span class="glyphicon glyphicon-pencil"></span>
                    </span>
                </h4>
                <p class="lead">
                    by <a href="index.php">Admin <span class="glyphicon glyphicon-user"></span></a>
                </p>
                <p><span class="glyphicon glyphicon-time"></span> Posted on @p.createDate.ToString()</p>
                <p>
                  @Html.Raw(@p.postText)
                 @*@Html.Raw(p.postText.Substring(0, (p.postText.Length)))*@
                </p>
                @Html.RouteLink("Read more..", new
                {
                    controller = "Post",
                    action = "viewPost",
                    postId = p.postId
                },
                             new
                             {
                                 @class = "btn btn-primary"
                             }
                   )
                      </div>
                </div>
            } @*// for loop ending*@

            <!-- Pager -->
            <ul class="pager">
                <li class="previous">
                    <a href="#">&larr; Older</a>
                </li>
                <li class="next">
                    <a href="#">Newer &rarr;</a>
                </li>
            </ul>
        </div>
    

blogProject/Views/Post/recentComments.cshtml
@model blogProject.Models.commentsListViewModel

@{
    ViewBag.Title = "postList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel-body">
    <h1 class="page-header">
        Top Recent Comments
        <small> 5 </small>
    </h1>
    @if (Model.commentsList.Count() <= 0)
    {
        <div class="panel panel-danger">
            <div class="panel-heading"><h4>Comments Search Error <span class="glyphicon glyphicon-question-sign"></span> </h4></div>
            <div class="panel-body">No recent comments avaliable  ?? <label class="btn-danger"></label></div>
        </div>    }
    <!-- First Blog Post -->
    @foreach (var p in Model.commentsList)
    {
        <h2>
            @Html.RouteLink(@p.commentTxt, new
       {
           controller = "Post",
           action = "viewPost",
           postId = p.postId
       })
            
        </h2>
        <p class="lead">
            by <a href="#">@p.user.userName <span class="glyphicon glyphicon-user"></span></a>
        </p>
        <p><span class="glyphicon glyphicon-time"></span> Posted on @p.commentDate.ToString()</p>
        <p>
            <label class="btn btn-danger">
                Post:@p.posts.postName
            </label>
           
        </p>
        @Html.RouteLink("Read more..", new
   {
       controller = "Post",
       action = "viewPost",
       postId = p.postId
   },
             new
             {
                 @class = "btn btn-primary"
             }
   )
        <hr>
    } @*// for loop ending*@

    <!-- Pager -->
    <ul class="pager">
        <li class="previous">
            <a href="#">&larr; Older</a>
        </li>
        <li class="next">
            <a href="#">Newer &rarr;</a>
        </li>
    </ul>
</div>

blogProject/Views/Post/recentPosts.cshtml
@model blogProject.Models.postViewModel

@{
    ViewBag.Title = "postList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel-body">
    <h1 class="page-header">
       Top Recent Posts 
        <small> 5 </small>
    </h1>
    @if (Model.posts.Count() <= 0)
    {
        <h2>No Post Added In This Month</h2>
    }
    <!-- First Blog Post -->
    @foreach (var p in Model.posts)
    {
        <h2>
            @Html.RouteLink(@p.postName, new
       {
           controller = "Post",
           action = "viewPost",
           postId = p.postId
       })
            <span class="label label-danger">
                @p.comments.Count()
                comments
            </span>
        </h2>
        <p class="lead">
            by <a href="index.php">Admin <span class="glyphicon glyphicon-user"></span></a>
        </p>
        <p><span class="glyphicon glyphicon-time"></span> Posted on @p.createDate.ToString()</p>
        <p >
            @Html.Raw(p.postText)
        </p>
        @Html.RouteLink("Read more..", new
   {
       controller = "Post",
       action = "viewPost",
       postId = p.postId
   },
             new
             {
                 @class = "btn btn-primary"
             }
   )
        <hr>
    } @*// for loop ending*@

    <!-- Pager -->
    <ul class="pager">
        <li class="previous">
            <a href="#">&larr; Older</a>
        </li>
        <li class="next">
            <a href="#">Newer &rarr;</a>
        </li>
    </ul>
</div>

blogProject/Views/Post/viewPost.cshtml
@model blogProject.Models.postdetailViewMode

@{
    ViewBag.Title = "viewPost";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    .blue {
        color: green;
    }

    .media:hover {
    }

    .commentMsgBorder {
        border-left: solid 5px;
        border-color: green;
        text-align: justify;
        font-family: Verdana, Geneva, Tahoma, sans-serif;
        color: cornflowerblue;
        font-weight: bold;
        white-space: pre-wrap; /* css-3 */
        word-wrap: break-word; /* Internet Explorer 5.5+ */
    }
</style>
<div class="row">
    <div class="col-lg-12">

        <div class="panel-body">
            <h2 class="page-header">
                <i class="label label-primary">
                    @Model.postDetails.postName
                </i>


            </h2>

            <span class="label label-danger">
                @Model.postDetails.comments.Count()
                comments <span class="glyphicon glyphicon-pencil"></span>
            </span>|
            <span class="label label-primary">
                @Model.postDetails.categorie.categoryName
                Category <span class="glyphicon glyphicon-bookmark"></span>
            </span>
            @{ 
                var statmentControl = false;
            }
            @*Below Statment first Authenticate that user is loged In or not*@
            @if (Model.currentUser.userId != 0 && Model.postDetails.favPosts.Count > 0)
            {
                foreach (var fav in Model.postDetails.favPosts.Where(c => c.userId == Model.currentUser.userId))
                {
                    if (fav.postId == Model.postDetails.postId && fav.userId == Model.currentUser.userId)
                    { 
                        <div>
                            <font size="5">
                                <a title="Remove from Favourite" href="@Url.Action("RemoveFromFavourite", "Post", new { postId = Model.postDetails.postId,userId=Model.currentUser.userId })"><i class="fa fa-heart"></i></a>
                            </font>
                        </div>
                        statmentControl = true;
                    }
                    else
                    {

                    }
                }

            }
            else if (Model.currentUser.userId != 0 && Model.postDetails.favPosts.Count <= 0)
            {

                <div>
                    <font size="5">
                        <a title="Add to Favourite" href="@Url.Action("addToFavourite", "Post", new { postId = Model.postDetails.postId,userId=Model.currentUser.userId })"><i class="fa fa-heart-o"></i></a>
                    </font>
                </div>

            }
            @if (Model.currentUser.userId != 0 && Model.postDetails.favPosts.Count > 0 && statmentControl == false)
            {
                <div>
                    <font size="5">
                        <a title="Add to Favourite" href="@Url.Action("addToFavourite", "Post", new { postId = Model.postDetails.postId,userId=Model.currentUser.userId })"><i class="fa fa-heart-o"></i></a>
                    </font>
                </div>
            }

            <!-- First Blog Post -->

            <p class="lead">
                by <a href="#myModal" data-toggle="modal">Admin <span class="glyphicon glyphicon-user"> </span></a>

            </p>
            @*The below code is chat Related to Post and now commented at the moment until further decesion When to Start Agian This portion*@
            @*@{
                    Html.RenderAction("postChat", "Chat", new {postId=Model.postDetails.postId });
                }*@
            <!-- Button trigger modal -->
            @*<div data-ng-controller="postController">
                </div>*@



            <p><span class="glyphicon glyphicon-time"></span><strong> Posted on @Model.postDetails.createDate.ToString("dd-MMMM-yyyy")</strong></p>
            <div>

            </div>
            <article>
                <p>
                    @Html.Raw(@Model.postDetails.postText)
                </p>
            </article>

            @if (TempData["newComment"] != null)
            {
                <div class="alert alert-success" role="alert">
                    <strong>Welcome!</strong>
                    @TempData["newComment"].ToString()
                </div>

            }
            @*Be The first to Comment if no comment on this post*@
            @if (Model.postDetails.comments.Count <= 0)
            {
                <div class="panel panel-success">
                    <div class="panel-heading"><h3>Welcome</h3> </div>
                    <div class="panel-body"><h4>Be the first one to comment on this Post</h4></div>
                </div>
            }

            <!-- Comments Form -->
            @{
                Html.RenderAction("leaveComment", "Nav", new { postId = Model.postDetails.postId, postName = Model.postDetails.postName });
            }
            <!-- Comments List -->

            @foreach (var comment in Model.postDetails.comments.OrderByDescending(j => j.commentDate))
            {

                if (comment.commentId == 2)
                {
                    <div class="media">

                        <a class="pull-left" href="#">
                            <img class="media-object" src="http://placehold.it/64x64" alt="">
                        </a>
                        <div class="well">
                            <h4 class="media-heading">
                                User <span class="glyphicon glyphicon-user"></span>
                                <small>@comment.commentDate</small>
                            </h4>
                            <p class="commentMsgBorder">@Html.Raw(@comment.commentTxt.ToString())</p>
                        </div>
                    </div>
                }
                else
                {
                    <div class="media">

                        <a class="pull-left" href="#">
                            @if (Model.currentUser.userId == comment.userId)
                            {
                                <img class="img-circle" src="~/Images/me.png" alt="">
                            }
                            else
                            {
                                <img class="img-circle" src="~/Images/you.png" alt="">
                            }

                        </a>
                        @*<div class="media-body">*@
                        <div class="media-heading">
                            @if (Model.currentUser.userId == comment.userId)
                            {
                                <label>@comment.user.userName</label>  <span class="glyphicon glyphicon-user blue"></span>
                            }
                            else
                            {
                                <label>@comment.user.userName</label>  <span class="glyphicon glyphicon-user"></span>
                            }
                            <small>@comment.commentDate.ToString("dd-MMMM-yyyy")</small>
                        </div>
                        <div class="media-body">
                            <p class="commentMsgBorder">@Html.Raw(@comment.commentTxt.ToString())</p>
                            @if (Model.currentUser.userId == comment.userId)
                            {
                                <a title="Delete My Comment" href="@Url.Action("delComment","Post",new {commentId=comment.commentId,url=Request.RawUrl })"><i class="fa fa-trash"></i></a>
                            }
                        </div>

                    </div>
                    @*</div>*@
                }

            } @*//-- comment for loop ending*@


        </div>
    </div>  @*// colum ending*@

</div> @*// Row ending*@  

blogProject/Views/Post/viewPostbyMonth.cshtml
@model blogProject.Models.monthSelectPostViewModel

@{
    ViewBag.Title = "postList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="panel-body">
    <h1 class="page-header">
        Month of : @Model.monthName - @Model.year
        <small> posts .. </small>
    </h1>
    @if (Model.posts.Count() <= 0)
    {
        <div class="panel panel-danger">
            <div class="panel-heading"><h4>Post Search Error <span class="glyphicon glyphicon-question-sign"></span> </h4></div>
            <div class="panel-body">No Post avaliable for the month of - <label class="btn-danger"> @Model.monthName</label></div>
        </div>
    }
    <!-- First Blog Post -->
    @foreach (var p in Model.posts)
    {
        <h2>
            @Html.RouteLink(@p.postName, new
       {
           controller = "Post",
           action = "viewPost",
           postId = p.postId
       })
            <span class="label label-danger">
                @p.comments.Count()
            comments
        </span>
    </h2>
        <p class="lead">
            by <a href="index.php">Admin <span class="glyphicon glyphicon-user"></span></a>
        </p>
        <p><span class="glyphicon glyphicon-time"></span> Posted on @p.createDate.ToString()</p>
        <p>
           @Html.Raw(p.postText)
        </p>
        @Html.RouteLink("Read more..", new
   {
       controller = "Post",
       action = "viewPost",
       postId = p.postId
   },
             new
             {
                 @class = "btn btn-primary"
             }
   )
        <hr>
    } @*// for loop ending*@

    <!-- Pager -->
    <ul class="pager">
        <li class="previous">
            <a href="#">&larr; Older</a>
        </li>
        <li class="next">
            <a href="#">Newer &rarr;</a>
        </li>
    </ul>
</div>