blogProject/Controllers/AdminController.cs
using BlogDal;
using BlogDal.Abstract;
using blogProject.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace blogProject.Controllers
{
  
    public class AdminController : Controller
    {
        private static string SessionKey = "userId";
          
        public class postValue
        {
            public int postId { get; set; }
            public string postText { get; set; }
            public string postName { get; set; }
            public int categoryId { get; set; }
        }
        public class categoryValue
        {
            public int categoryId { get; set; }
            public string categoryName { get; set; }

        }
        // GET: Admin
        private IpostRepository Postrepository;
        private IadminRepository adminRepository;
        public AdminController(IpostRepository prmRepository,IadminRepository prmadminRepository)
        {
            Postrepository = prmRepository;
            adminRepository = prmadminRepository;
        }
        public ActionResult PostList()
        {
            postViewModel postListViewModel = new postViewModel();
            if (ControllerContext.HttpContext.Session[SessionKey]==null)
            {
                return RedirectToAction("LogPagee", "Account", new { returnUrl =Request.RawUrl});
            }
            if (ControllerContext.HttpContext.Session[SessionKey]!=null)
            {
                User currentUser = (User)ControllerContext.HttpContext.Session[SessionKey];
                if (currentUser.name.ToLower()!="admin")
                {
                    return RedirectToAction("greetMessage", new messageViewModel() { userName = currentUser.name, message = " You Have No access for this section of web site ???" });
                }

            }
            postListViewModel.posts = Postrepository.posts.ToList();
            return View();
        }

        public ActionResult EditPost(int postid=0)
        {
            var value =Postrepository.posts.Where(c => c.postId == postid).Select(x=> new {postId=x.postId,postText=x.postText }).FirstOrDefault();
            postValue EditPostViewModel = new postValue();
            EditPostViewModel.postId = value.postId;
            EditPostViewModel.postText = value.postText;
            return View(EditPostViewModel);
        }

        [HttpPost]
        public ActionResult EditPosts(postValue value)
        {
            post dbPost = new BlogDal.post() { postId = value.postId, postName = value.postName, postText = value.postText, categoryId = value.categoryId };
            Postrepository.Save(dbPost);
            //return RedirectToAction("PostList","Admin");
            var postView = Postrepository.posts.Select(x => new { postId = x.postId, postname = x.postName, posttext = x.postText, cratedOn = x.createDate, commentCount = x.comments.Count() }).Where(c => c.postId == dbPost.postId).FirstOrDefault();

            return Json(postView, JsonRequestBehavior.AllowGet);


        }
        [HttpPost]
        public ActionResult saveCategory(categoryValue catValue)
        {
            categorie dbCategory = new categorie();
            dbCategory.categoryId = catValue.categoryId;
            dbCategory.categoryName = catValue.categoryName;
            Postrepository.savePostCategory(dbCategory);
            catValue.categoryId = dbCategory.categoryId;
            return Json(catValue, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult jsViewPost ( int postId)
        {
            var postDetails = Postrepository.posts.Where(c => c.postId == postId).Select(x => new {postId=x.postId,postname=x.postName,posttext=x.postText, categoryId=x.categoryId }).FirstOrDefault();
            return Json(postDetails, JsonRequestBehavior.AllowGet);
        }
        public ActionResult jsGetCategory ()
        {
            var cateoriesList = Postrepository.categories.Select(x => new {categoryId=x.categoryId,categoryName=x.categoryName });
            return Json(cateoriesList, JsonRequestBehavior.AllowGet);
        }
        public ActionResult show()
        {
            return View();
        }
        public ActionResult jsViewPostList()
        {
            var PostListView = Postrepository.posts.Select(x => new { postId = x.postId, postname = x.postName, posttext = x.postText,cratedOn=x.createDate,commentCount=x.comments.Count() }).ToList();
            return Json(PostListView, JsonRequestBehavior.AllowGet);

        }
        public ActionResult jsViewComments(int postId)
        {
            var postComments = Postrepository.comments.Where(c => c.postId == postId).Select(x => new {commentId=x.commentId,commentTxt=x.commentTxt,commentDate=x.commentDate }).ToList();
            return Json(postComments, JsonRequestBehavior.AllowGet);
        }
        [HttpGet]
        public ActionResult deleteComments(int commentId=0)
        {
            Postrepository.delComment(commentId);
            return Json(commentId.ToString(), JsonRequestBehavior.AllowGet);

        }
       
        public ActionResult greetMessage(messageViewModel greetMessage)
        {
            return View("messagePage", greetMessage);
        }
        public ActionResult Contact(contactus ContactUs )
        {
            ContactUs.contactDate = DateTime.Now;
            if (ModelState.IsValid)
            {
                adminRepository.ContactUs(ContactUs);
                messageViewModel greetMessage = new messageViewModel();
                greetMessage.userName = ContactUs.contactName;
                greetMessage.message = "Thaks for Your Message .. I will contact you soon ??";
                // Save the Message to database and then redirect the page to GreetingPage
                return RedirectToAction("greetMessage", greetMessage);
            }
            else
            {
                return View(ContactUs);
            }
           
        }
       

    }
}

blogProject/Controllers/ChatController.cs
using BlogDal;
using BlogDal.Abstract;
using blogProject.Helper;
using Microsoft.AspNet.SignalR;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;

namespace blogProject.Controllers
{
    public class CustomJsonResult : JsonResult
    {
        private const string _dateFormat = "yyyy-MM-dd HH:mm:ss";

        public override void ExecuteResult(ControllerContext context)
        {
            if (context == null)
            {
                throw new ArgumentNullException("context");
            }

            HttpResponseBase response = context.HttpContext.Response;

            if (!String.IsNullOrEmpty(ContentType))
            {
                response.ContentType = ContentType;
            }
            else
            {
                response.ContentType = "application/json";
            }
            if (ContentEncoding != null)
            {
                response.ContentEncoding = ContentEncoding;
            }
            if (Data != null)
            {
                // Using Json.NET serializer
                var isoConvert = new IsoDateTimeConverter();
                isoConvert.DateTimeFormat = _dateFormat;
                response.Write(JsonConvert.SerializeObject(Data, isoConvert));
            }
        }
    }// end of class
    public class grouoMessageViewModel
    {
        public int groupChatId { get; set; }
        public int uid { get; set; }
        public string name { get; set; }
        public string msg { get; set; }
        public string groupd { get; set; }
        public string time { get; set; }
        public string txtType { get; set; }
    }
    public class ChatController : Controller
    {
        public IgroupRepository gRepository;
        private IuserRepository repository;

        // GET: Chat
        private static string SessionKey = "userId";

        public  ChatController(IgroupRepository prmRepository,IuserRepository prmUserRepository)
        {
            gRepository = prmRepository;
            repository = prmUserRepository;
        }
        [HttpGet]
        public  ActionResult getFiles(int groupId)
        {
            var values = (from x in gRepository.groupChats
                       where (x.groupId == groupId && x.txtType == "imagetxt")
                       select new {userId = x.userId, fileName = x.chatTxt }).ToList();

            //var values= gRepository.getFileNames(groupId);
            return Json(values, JsonRequestBehavior.AllowGet);

        }
        

        [HttpGet]
        public ActionResult getChat(int groupId,int pageCount)
        {
            int groupToMestalsages = gRepository.GroupMessageTotal(groupId);
            int skippTotal = pageCount * 30;
            if (skippTotal<groupToMestalsages && (groupToMestalsages-skippTotal)<30 )
            {
                skippTotal = groupToMestalsages;

            }
            var groupChat = (from p in gRepository.groupChats
                             where p.groupId == groupId
                             select new
                             {
                                 groupChatId = p.groupChatId,
                                 uid = p.userId,
                                 name = p.users.userName,
                                 msg = p.chatTxt,
                                 groupd = p.groups.groupName,
                                 time = p.txtDate,
                                 txtType = p.txtType
                             }).
                            ToList()
                            .Select(x => new grouoMessageViewModel()
                            {
                                groupChatId=x.groupChatId,
                                uid=x.uid,
                                name=x.name,
                                msg=x.msg,
                                groupd=x.groupd,
                                time=x.time.ToString("s"),
                                txtType=x.txtType


                            }).ToList().Skip(groupToMestalsages-skippTotal).Take(skippTotal);
                            

            
               
             
              //  Select(x => new { groupChatId = x.groupChatId, uid = x.users.userId, name = x.users.userName, msg = x.chatTxt, group = x.groups.groupName, time = x.txtDate, txtType = x.txtType });
            return Json(groupChat, JsonRequestBehavior.AllowGet);
           // return new CustomJsonResult { Data = new { chats = groupChat } };

        }
        [HttpPost]
        public JsonResult SaveFiles(string description)
        {
            string Message, fileName, actualFileName;
            Message = fileName = actualFileName = string.Empty;
            bool flag = false;
            string path = "";
            if (Request.Files != null)
            {
                var file = Request.Files[0];
                actualFileName = file.FileName;
                fileName = Guid.NewGuid() + Path.GetExtension(file.FileName);
                int size = file.ContentLength;
                try
                {
                    path = Server.MapPath("~/Images");
                    file.SaveAs(Path.Combine(path, fileName));

                    Message = fileName;
                    flag = true;

                }
                catch (Exception)
                {
                    Message = "Failed";

                    flag = false;
                }


            }

            return new JsonResult { Data = new { Message = Message, Status = flag } };
        }
        public ActionResult testing()
        {
            return View();
        }
        [HttpGet]
        [Route("ChatController")]

        public ActionResult getUserId ()
        {
            var userDetails = ControllerContext.HttpContext.Session[SessionKey];
            return Json(userDetails, JsonRequestBehavior.AllowGet);

        }
        [HttpGet]
        public ActionResult verifyUserAndGetUser(string userName, string password, HttpRequestMessage request)
        {
          // var d= request.GetClientIpAddress();
            user prmUser = new user
            {
                userName = userName,
                password = password
            };
            user dbUser = repository.verifyUser(prmUser);
            //    FormsAuthentication.SetAuthCookie("junaid",false); // This statment is for Temporarly purpose  only 
            if (dbUser != null)
            {
                User usr = new User();
                usr.userId = dbUser.userId;
                usr.name = dbUser.userName;
                this.HttpContext.Session.Timeout = 60;
                ControllerContext.HttpContext.Session[SessionKey] = usr;

                
                 var ip = this.Request.ServerVariables["REMOTE_ADDR"];
                //ip = "92.0.164.122";
                var country = Helper.GeoLocation.IPRequestHelper(ip);
                repository.saveCountry(dbUser.userId, country);
            }
            var userDetails = ControllerContext.HttpContext.Session[SessionKey];
            if (userDetails!=null)
            {
               return  RedirectToAction("ChatRoom", "chat");

            }

            return Json(userDetails, JsonRequestBehavior.AllowGet);


        } // end of action Method
        [HttpGet]
        public ActionResult registerNewUser(string name,string password)
        {
            User usr = new User();

            user prmUser = new user()
            {
                userName=name,
                password=password
            };
            if (repository.checkUser(prmUser))
            {
                
            }
            else
            {
                repository.Create(prmUser);
                usr.userId = prmUser.userId;
                usr.name = prmUser.userName;
                ControllerContext.HttpContext.Session[SessionKey] = usr;
            }
            return Json(usr, JsonRequestBehavior.AllowGet);


        }
        [HttpGet]
        public ActionResult getId()
        {
            var userDetails = ControllerContext.HttpContext.Session[SessionKey];
            return Json(userDetails, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ChatRoom()
        {
            //if (ControllerContext.HttpContext.Session["UserId"] == null)
            //{
            //    ViewBag.invalid = "You need to give Log Dtails to Start Chatting ....";
            //  return RedirectToAction("LogPagee", "Account",new {returnUrl= Request.RawUrl } );
            //}
            //else 
            return View();
        }
        public ActionResult chatManage()
        {
            return View();
        }
        public ActionResult postChat(int postId)
        {
            ControllerContext.HttpContext.Session["postId"] = postId;
            return View();
        }
        public ActionResult mapChat()
        {
            return View();
        }
    }
}

blogProject/Views/Nav/AdminOptions.cshtml
<div class="row">
    <div class="col-lg-12">
       
           <a href=@Url.Action("userManage","Account") class="btn btn-primary btn-lg">
               Manage Users <span class="glyphicon glyphicon-user"></span>
           </a>
       <hr />
        
            <a href=@Url.Action("PostList","Admin") class="btn btn-primary btn-lg">
                Manage Post <span class="glyphicon glyphicon-book"></span><span class="glyphicon glyphicon-book"></span>
            </a>
        <hr />
        <a href=@Url.Action("chatManage","Chat") class="btn btn-primary btn-lg">
            Manage Chat <span class="glyphicon glyphicon-comment"></span><span class="glyphicon glyphicon-comment"></span>
        </a>
        <hr />
        <a href=@Url.Action("manageProject","Admin") class="btn btn-primary btn-lg">
            Manage Projects <span class="glyphicon glyphicon-bookmark"></span>
        </a>

    </div>
    

</div>

blogProject/Views/Nav/LogInnandOut.cshtml
@model blogProject.Models.LoguserViewModel
<div class="top-menu">
    <ul class="nav pull-right top-menu">
        <li>
          
            @if (Model.userName != null)
            {
                <div class="input-group">
                    <a href="@Url.Action("LogOut","Account", new {returnUrl=Request.RawUrl })" class="btn btn-success btn-lg active"><strong>Log Out:</strong>  @Model.userName <span class="glyphicon glyphicon-user"></span></a>
                    <a href="@Url.Action("myProfile","Account", new {returnUrl=Request.RawUrl })" class="btn btn-success btn-lg active"><strong>My Profile</strong>  <span class="glyphicon glyphicon-info-sign"></span></a>

                </div>


            }
            else
            {
                <a href="@Url.Action("LogPagee","Account", new {returnUrl=Request.RawUrl })" class="btn btn-primary btn-lg active">Log Inn <span class="glyphicon glyphicon-user"></span></a>

            }

        </li>
        

    </ul>
</div>

blogProject/Views/Nav/archiveList.cshtml
@model blogProject.Models.archiveViewMode

<div class="panel panel-default">
    <div class="panel-heading">
        <label type="button" class="btn btn-primary">
            Archive History <span class="glyphicon glyphicon-calendar"></span>
        </label>
        
    </div>
    
        <ul class="list-group">




            @foreach (var arch in Model.listArchive)
            {

                <li class="list-group-item">
                   
                    <span class="glyphicon glyphicon-camera"></span>

                    @Html.RouteLink(arch.MonthName + "-" + arch.Year.ToString(),
                              new
                              {
                                  controller = "Post",
                                  action = "viewPostbyMonth",
                                  monthId = arch.MonthName,
                                  year  = arch.Year
                              })


                    @*<span class="badge"> @month.Value.ToString()</span>*@


                </li>


            } @*foreach loop ending*@


        </ul>

   
</div>

blogProject/Views/Nav/leaveComment.cshtml
@model blogProject.Models.leaveCommentModel
 <style>
     #leaveCommentArea:focus{
         border:thick solid green;
     }
 </style>
  @if (Model.loged)
    {
        <div class="well">
            <h4><strong>Comment</strong> <span class="glyphicon glyphicon-pencil"></span> </h4>
            @using (Html.BeginForm("postComment", "Post"))
            {

                <div class="form-group">
                    <input  type="hidden" name="postId" value="@Model.postId" />
                    <input type="hidden" name="postName" value="@Model.postName" />
                    <textarea id="leaveCommentArea" name="commenttext" class="form-control input-lg" rows="3" required autofocus></textarea>
                </div>
                <button type="submit" class="btn btn-primary btn-lg">Leave Comment <span class="glyphicon glyphicon-pencil"></span> </button>

            }
        </div>
    }
    else
    {
        <div class="well">
            
            <div class="alert alert-success" role="alert">
                <strong>Alert!</strong><h4> To Leave a Comment: SignInn </h4>
            </div>
                <a href="@Url.Action("LogPagee","Account", new {returnUrl=Request.RawUrl })" class="btn btn-primary btn-lg">Sign In <span class="glyphicon glyphicon-user"></span></a>

            </div>

    }

blogProject/Views/Nav/postCategory.cshtml
@model blogProject.Models.categoriesViewModel
<div class="panel panel-default">
    <div class="panel-heading">
        <label type="button" class="btn btn-primary">
            Post Categories <span class="glyphicon glyphicon-comment"></span>
        </label>

    </div>
   
    
        <ul class="list-group">
            @foreach (var category in Model.listCategories)
            {
                <li class="list-group-item">
                    <span class="glyphicon glyphicon-book"></span>
                    
                        @Html.RouteLink(category.categoryName,
                  new
                  {
                      controller = "Post",
                      action = "postList",
                      categoryId = category.categoryId

                  })
                    
                </li>
            } @*<! --- For loop ending-->*@
           
        </ul>
   
    
</div>

blogProject/Views/Nav/postFavourite.cshtml
@model blogProject.Models.favouriteViewModel
    @if (Model.userId != 0)
    {
        <div class="panel panel-default" style="border:none">
            <div class="panel-heading">
                <label type="button" class="btn btn-primary" data-toggle="collapse" data-target="#demo">
                    Favourites <span class="glyphicon glyphicon-comment"></span>
                </label>
            </div>
            <div id="demo" class="collapse">
                <ul class="list-group">
                    @foreach (var favPost in Model.favPostList)
                    {
                        <li class="list-group-item">
                            <span class="glyphicon glyphicon-book"></span>

                            @Html.RouteLink(favPost.posts.postName,
                  new
                  {
                      controller = "Post",
                      action = "viewPost",
                      postid = favPost.postId

                  })

                        </li>
                    } 

                </ul>
            </div>
        </div>

    }

blogProject/Views/Nav/postList.cshtml
@model blogProject.Models.postViewModel
<style>
   #postList>li:hover{
        border:thin solid green;
        text-decoration:none;
        background-color:lightgrey;
    }
  
</style>
<div class="panel panel-default">
    <div class="panel-heading">
        <a href="@Url.Action("recentPosts", "Post")" class="btn btn-primary" >Recent Posts <span class="glyphicon glyphicon-comment"></span></a>
       
    </div>

    
        <ul id="postList" class="list-group">
            @foreach (var post in Model.posts)
            {
                <li class="list-group-item">
                    <span class="badge">@post.comments.Count() <span class="glyphicon glyphicon-comment"></span></span>
                   @Html.RouteLink(post.postName,
                  new {
                      controller ="Post",
                      action ="viewPost",
                      postId = post.postId

                  })
                </li>

            } @*foreach loop ending*@
           
        </ul>
</div>

blogProject/Views/Nav/recentComments.cshtml
@model blogProject.Models.commentsListViewModel
<div  class="panel panel-default">
    <div class="panel-heading">
        <a href="@Url.Action("recentComments", "Post")" class="btn btn-primary">Recent Comments <span class="glyphicon glyphicon-comment"></span>
        </a>

        @*<label type="button" class="btn btn-primary">
            Recent Comments <span class="glyphicon glyphicon-comment"></span>
        </label>*@
        
    </div>
    

    
        <ul class="list-group">
            @foreach (var comment in Model.commentsList)
            {
                <li class="list-group-item">
                    <a href=@Url.RouteUrl("Default",new  {controller="Post",Action="viewpost", postId=comment.postId })>
                        <span> <span class="glyphicon glyphicon-comment"></span> 
                        @if (comment.commentTxt.Length>25)
                        {
                           @comment.commentTxt.Substring(0,25)

                     
                        }
                        else
                        {
                            @comment.commentTxt.ToString()
                        }
                        </span>

                    </a>
                   
                     
                </li>
            }
        </ul> 
    
    
   
</div>



@*<div class="panel panel-default">
    <div class="panel-heading">
       
            <a href="@Url.Action("recentComments", "Post")" class="btn btn-primary">Recent Comments <span class="glyphicon glyphicon-comment"></span></a>


    </div>
    <ul class="list-group">
        <li class="list-group-item"><a href="#">I don't believe in astrology but still your writing style is really great! - <em>john</em></a></li>
        <li class="list-group-item"><a href="#">Wow.. what you said is really true! I'm an aries though - <em>Anto</em></a></li>
        <li class="list-group-item"><a href="#">Does capricorn and aries is compatibile? - <em>Sarah</em></a></li>
        <li class="list-group-item"><a href="#">I'm a cancer woman been in love with Leo. Will this work? - <em>Mary</em></a></li>
    </ul>
</div>*@